version: 0.1
log:
  level: error
  accesslog:
    disabled: true
  fields:
    service: docker-registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
middleware:
  storage:
    - name: ecr
      options:
        local: docker-registry.service.consul:5000
        remote: 123456789012.dkr.ecr.us-east-1.amazonaws.com
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3